sudo: required
dist: trusty

language: go

go:
  - 1.8

services:
  - rabbitmq
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

before_script:
  - install/build_docker_images.sh

script:
  - go test -v $(go list ./... | grep -v /vendor/)

